const {app}=require("electron"),fs=require("node:fs"),path=require("node:path"),assert=require("node:assert/strict"),{waitFor,assertLayout,settleUI}=require("./layout-check.cjs");
const profile=process.env.STREAMER_ASSIST_TEST_PROFILE;app.setPath("userData",profile);fs.mkdirSync(profile,{recursive:true});fs.writeFileSync(path.join(profile,"preferences.json"),JSON.stringify({autoRecord:false,trayEnabled:true,shortcut:"CommandOrControl+Alt+Shift+F13"}));process.env.STREAMER_ASSIST_SHORTCUT="CommandOrControl+Alt+Shift+F13";
let engine;const platform=require("../electron/platforms.cjs"),original=platform.Platforms;platform.Platforms=class extends original{constructor(...args){super(...args);engine=this.engine;}};
const providers=require("../electron/replay-providers.cjs"),actual=providers.ReplayProviders;
providers.ReplayProviders=class extends actual{async discover(session){return[{platform:"youtube",videoId:"abcdefghijk",url:"https://www.youtube.com/watch?v=abcdefghijk",startedAt:session.startedAt},{platform:"twitch",videoId:"123",url:"https://www.twitch.tv/videos/123",startedAt:session.startedAt},{platform:"chzzk",videoId:"456",url:"https://chzzk.naver.com/video/456",startedAt:session.startedAt}];}async *collect(source){for(let page=0;page<2;page++){const message={platform:source.platform,id:source.videoId+"-"+page,userId:"u"+page,name:"다시보기 시청자",text:"원본 다시보기 "+page,timestamp:source.startedAt+1000+page*1000,offsetMs:1000+page*1000};yield{messages:[message],cursor:page+1,source,verification:source.platform==="chzzk"?"unofficial-pagination":"fixture-replay"};}}};
const timer=setTimeout(()=>{console.error("Replay desktop test timed out");app.exit(1);},30000);
// Keep frame-based UI checks running when another desktop window covers this fixture.
app.on("browser-window-created",(_event,win)=>win.webContents.setBackgroundThrottling(false));
app.once("browser-window-created",(_e,win)=>win.webContents.once("did-finish-load",async()=>{
  const js=(fn,...args)=>win.webContents.executeJavaScript("("+fn.toString()+")("+args.map(JSON.stringify).join(",")+")");
  const call=async(action,payload={})=>{const r=await js((a,p)=>window.assist.call(a,p),action,payload);assert.ok(r.ok,r.error);return r.data;};
  try{await waitFor(()=>js(()=>!!document.querySelector('[data-workspace-ready="true"]')),"workspace ready");
    await call("capture-mode-set",{mode:"replay",autoAnalyze:false});await call("start",{title:"실시간 기능만"});assert.equal(engine.current.chatCaptureMode,"replay");engine.createPoll("Q",["A","B"],"chat",["chzzk"],"!",null);
    for(let i=0;i<50;i++)engine.ingest({platform:"chzzk",id:"live"+i,userId:"live"+i,name:"live",text:"!1",timestamp:Date.now()});engine.sampleViewers([{platform:"chzzk",live:true,viewers:12345}],Date.now());engine.mark("보존할 마커");await call("state");assert.equal(engine.poll.counts[0],50);
    const id=engine.current.id;await call("stop");const before=await call("timeline-history",{sessionId:id,limit:100});assert.equal(before.events.length,0,"replay mode does not save live chat");
    await js(()=>window.assist.workspace("open",{id:"timeline"}));await waitFor(()=>js(()=>!!document.querySelector(".telemetry-tabs")),"timeline lazy loaded");await js(()=>[...document.querySelectorAll(".telemetry-tabs button")].find(b=>b.textContent.trim()==="다시보기 수집").click());await waitFor(()=>js(()=>!!document.querySelector(".replay-workspace")),"replay page");
    win.setSize(900,650);await settleUI(win);await assertLayout(win,"replay-900");assert.equal(await js(()=>document.querySelector('[aria-label="다시보기 영상 주소"]').value),"");
    await call("text-scale-set",{scale:150});await settleUI(win);await assertLayout(win,"replay-150-900");
    await js(()=>document.querySelector('.settings-tab').click());await waitFor(()=>js(()=>!!document.querySelector('.settings-tabs')),"settings ready");await js(()=>[...document.querySelectorAll('[role="tab"]')].find(b=>b.textContent.includes("방송 기록")).click());await settleUI(win);await assertLayout(win,"capture-settings-150-900");assert.equal(await js(()=>document.querySelector('[aria-label="채팅 수집 방식"]').value),"replay");
    await js(()=>window.assist.workspace("open",{id:"timeline"}));await call("text-scale-set",{scale:100});await settleUI(win);
    await call("replay-start",{sessionId:id,analyze:true});await waitFor(async()=>{const data=await call("replay-state");return data.jobs.find(j=>j.sessionId===id)?.status==="completed";},"post-broadcast sources merged",12000);
    const records=await call("timeline-history",{sessionId:id,limit:100});assert.equal(records.events.length,6);assert.deepEqual([...new Set(records.events.map(e=>e.platform))].sort(),["chzzk","twitch","youtube"]);assert.ok(records.events.every(e=>e.origin==="vod-replay"));
    const session=engine.sessions.find(s=>s.id===id);assert.ok(session.markers.some(m=>m.label==="보존할 마커"));assert.deepEqual(session.polls[0].counts,[50,0]);assert.equal(session.telemetry.viewerSamples,1);const analysis=await call("timeline-analysis",{sessionId:id});assert.equal(analysis.chats,6);assert.equal(analysis.viewers.length,1);
    await call("state");await settleUI(win);await assertLayout(win,"replay-completed-900");
    console.log("PASS: actual Electron modes, no live raw chat in replay mode, active voting/viewers/markers, three-platform VOD merge, provenance, post analysis and bounded 900x650 UI");clearTimeout(timer);app.quit();
  }catch(error){console.error(error);const output=path.join(__dirname,"../release/replay-failure.png");fs.writeFileSync(output,(await win.webContents.capturePage()).toPNG());console.error(await js(()=>[...document.querySelectorAll('.replay-workspace,.replay-grid,.replay-sources,.replay-controls')].map(e=>({class:e.className,bounds:e.getBoundingClientRect().toJSON(),height:getComputedStyle(e).height}))));clearTimeout(timer);app.exit(1);}
}));require("../electron/main.cjs");
