import {useEffect,useRef,useState} from "react";
import {useTabState} from "./workspace-state";
import {usePageActive} from "./activity";
import {Icon,PlatformIcon} from "./icons";
import type {TimelineSession} from "./timeline-types";
import "./replay.css";
export type ReplaySource={platform:"youtube"|"twitch"|"chzzk";videoId:string;url:string;startedAt:number;cursor?:number;saved?:number;completed?:boolean;verification?:string;match?:string;title?:string};
export type ReplayJob={sessionId:string;sessionTitle?:string;status:string;sources:ReplaySource[];received:number;saved:number;analyze:boolean;error?:string;progress?:{message?:string;cursor?:number}};
export type ReplayState={jobs:ReplayJob[];tools:{platform:string;name:string;version:string;installed:boolean;busy:boolean}[];error?:string};
const statuses:Record<string,string>={waiting:"다시보기 준비 대기",discovering:"방송 영상 찾는 중",running:"채팅 가져오는 중",paused:"수집 일시 중지",failed:"수집 확인 필요",completed:"가져오기 완료",analyzing:"통계·하이라이트 계산 중"};
async function request<T>(action:string,payload?:unknown):Promise<T>{const result=await window.assist?.call(action,payload);if(!result?.ok)throw Error(result?.error||"다시보기 작업을 실행하지 못했습니다.");return result.data as T;}
export function ReplayWorkspace({session,state,onChanged}:{session?:TimelineSession;state?:ReplayState;onChanged?:()=>void}){
  const active=usePageActive();const [current,setCurrent]=useState(state);const [sources,setSources]=useTabState<ReplaySource[]>("replay.sources",[]);const [url,setUrl]=useState("");const [analyze,setAnalyze]=useTabState("replay.analyze",false);const [speed,setSpeed]=useTabState("replay.speed","2");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const input=useRef<HTMLInputElement>(null);
  const job=current?.jobs.find(j=>j.sessionId===session?.id),running=!!job&&["running","discovering","analyzing"].includes(job.status);
  useEffect(()=>setCurrent(state),[state]);
  useEffect(()=>{if(!active)return;let live=true,pending=false;const update=async()=>{if(pending)return;pending=true;try{const next=await request<ReplayState>("replay-state");if(live)setCurrent(next);}catch{}finally{pending=false;}};void update();const timer=running?setInterval(()=>void update(),1000):undefined;return()=>{live=false;clearInterval(timer);};},[active,running,session?.id]);
  useEffect(()=>{setSources([]);setMessage("");},[session?.id]);
  const act=async(action:string,payload:unknown)=>{setBusy(true);setMessage("");try{const data=await request(action,payload);onChanged?.();setCurrent(await request<ReplayState>("replay-state"));return data;}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
  const add=()=>{try{const parsed=new URL(url.trim());const host=parsed.hostname;const platform=["youtube.com","www.youtube.com","m.youtube.com","youtu.be"].includes(host)?"youtube":["twitch.tv","www.twitch.tv"].includes(host)?"twitch":host==="chzzk.naver.com"?"chzzk":null;if(!platform||parsed.protocol!=="https:")throw Error("YouTube·Twitch·치지직 영상 주소를 입력하세요.");if(!sources.some(s=>s.url===url.trim()))setSources([...sources,{platform,url:url.trim(),videoId:"",startedAt:session?.startedAt||Date.now()}]);setUrl("");setMessage("");input.current?.focus();}catch(e){setMessage((e as Error).message);}};
  return <div className="replay-workspace">
    <section className="panel replay-heading"><div><h2><Icon name="timeline" size={18}/> 방송 종료 후 채팅 수집</h2><p>방송 당시의 마커·시청자 수에 다시보기 채팅을 연결합니다.</p></div><span className="pill">{job?statuses[job.status]||job.status:session?.endedAt?"영상 선택":"방송 종료 후 사용"}</span></section>
    <div className="replay-grid"><section className="panel replay-sources"><div className="replay-section-title"><h3>다시보기 영상</h3><button className="secondary small" disabled={busy||running||!session?.endedAt} onClick={()=>void act("replay-discover",{sessionId:session?.id}).then(data=>{if(Array.isArray(data)){setSources(data as ReplaySource[]);if(!data.length)setMessage("연결할 영상을 찾지 못했습니다. 다시보기 주소를 추가하세요.");}})}>연결된 방송에서 찾기</button></div>
      <form className="replay-add" onSubmit={e=>{e.preventDefault();add();}}><input ref={input} aria-label="다시보기 영상 주소" placeholder="YouTube·Twitch·치지직 다시보기 URL" value={url} disabled={running} onChange={e=>setUrl(e.target.value)}/><button className="secondary" disabled={running||!url.trim()}>추가</button></form>
      <div className="replay-source-list">{sources.length?sources.map((s,i)=><div className="replay-source" key={s.url}><PlatformIcon platform={s.platform} size={20}/><div><strong>{s.title||s.url}</strong><label>영상 시작 시각 <input type="datetime-local" aria-label={`영상 ${i+1} 시작 시각`} value={new Date(s.startedAt-new Date(s.startedAt).getTimezoneOffset()*60000).toISOString().slice(0,16)} disabled={running} onChange={e=>{const at=new Date(e.target.value).getTime();if(Number.isFinite(at))setSources(sources.map((r,n)=>n===i?{...r,startedAt:at}:r));}}/></label></div><button className="icon-button" aria-label={`영상 ${i+1} 제거`} disabled={running} onClick={()=>setSources(sources.filter((_,n)=>n!==i))}><Icon name="close" size={16}/></button></div>):<div className="telemetry-empty"><Icon name="timeline" size={26}/><strong>방송의 다시보기를 선택하세요</strong><span>하루에 여러 영상이 생긴 경우 하나씩 추가할 수 있습니다.</span></div>}</div>
      <div className="replay-controls"><label>수집 속도 <select value={speed} disabled={running} onChange={e=>setSpeed(e.target.value)}><option value="1">가볍게 · 초당 1회</option><option value="2">기본 · 초당 2회</option><option value="5">빠르게 · 초당 5회</option></select></label><label><input type="checkbox" checked={analyze} disabled={running} onChange={e=>setAnalyze(e.target.checked)}/> 가져온 뒤 통계·하이라이트 계산</label><div><button className="primary" disabled={busy||running||!session?.endedAt} onClick={()=>void act("replay-start",{sessionId:session?.id,...(sources.length?{sources}:{}),analyze,requestsPerSecond:Number(speed)})}>채팅 가져오기</button>{job&&["running","waiting","discovering"].includes(job.status)&&<button className="secondary" onClick={()=>void act("replay-cancel",{sessionId:session?.id})}>일시 중지</button>}<button className="secondary" disabled={busy||running||!session?.endedAt} onClick={()=>void act("replay-analyze",{sessionId:session?.id})}>저장한 기록 분석</button></div></div>
    </section><section className="panel replay-status"><h3>수집 상태</h3><div className="replay-numbers"><span>가져온 채팅<strong>{(job?.saved||session?.telemetry?.chats||0).toLocaleString()}</strong></span><span>영상<strong>{job?.sources.filter(s=>s.completed).length||0} / {job?.sources.length||sources.length}</strong></span></div>
      {(message||job?.error||current?.error)&&<p className="replay-error" role="alert">{message||job?.error||current?.error}</p>}
      {job?.progress?.message&&running&&<p className="replay-progress">{job.progress.message}</p>}
      <div className="replay-note"><strong>다시보기에 남은 채팅</strong><p>삭제된 영상·채팅과 제공되지 않는 메시지는 가져올 수 없습니다. 플랫폼 내부 조회 경로는 변경될 수 있으며 전체 전달을 보장하지 않습니다.</p><p>시청자 수와 실시간 투표·추첨은 방송 중에만 기록합니다. 후원 정보는 다시보기에서 제공되는 범위만 포함합니다.</p></div>
      <h3>선택 다운로드 도구</h3><div className="replay-tools">{current?.tools.map(t=><div key={t.platform}><div><strong>{t.name}</strong><small>{t.version} · {t.installed?"설치됨":"필요할 때 다운로드"}</small></div><button className="secondary small" disabled={t.busy||running} onClick={()=>void act(t.installed?"replay-tool-remove":"replay-tool-install",{platform:t.platform})}>{t.busy?"다운로드 중":t.installed?"제거":"다운로드"}</button></div>)}</div><small>영상 파일은 다운로드하지 않습니다. 도구는 앱 전용 경로에서만 사용합니다.</small>
    </section></div>
  </div>;
}
